# Generated by Django 4.1.1 on 2022-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_p_min_product_p_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(default='category/vid.jpg', upload_to='category'),
        ),
    ]
