# Generated by Django 4.1.1 on 2022-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='category-img/model6.jpg', upload_to='category-img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(default='category/vid4.mp4', upload_to='category'),
        ),
    ]
